name: Github Actions Runner Tree
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Where am I
        run: pwd
      - name: Display tree of default runners dir
        run: sudo tree -f -L 1
      - name: Display tree of root runners dir
        run: |
          cd /
          sudo tree -f -L 1
      - name: Check out repository onto the runner
        uses: actions/checkout@v3
      - name: Display tree of default runners dir
        run: sudo tree -f -L 1
      